---
- name: Install additional packages via curl
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.destination }}"
    force: true
    owner: root
    group: root
    mode: 0755
  with_items: curl_global_packages