---
- include: server_bootstrap.yml
- hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  vars_files:
    - ../vars/webservers.yml
    - ../vars/dbservers.yml
  roles:
    - role: ANXS.mysql
    - role: geerlingguy.php
    - role: kosssi.php # Used to upgrade php to v5.6
    - role: geerlingguy.nginx
    - role: geerlingguy.composer
    - role: Stouts.postfix
    - role: Stouts.nodejs
    - role: curl_packages